export enum AddressType {
  REGISTRATION_ADDRESS = 'REGISTRATION_ADDRESS',
  RESIDENCE_ADDRESS = 'RESIDENCE_ADDRESS',
  LEGAL_ENTITY_ADDRESS = 'LEGAL_ENTITY_ADDRESS',
  POSTAL_ADDRESS = 'POSTAL_ADDRESS',
  OFFICE_OF_FOREIGN_LEGAL_ENTITY_ADDRESS = 'OFFICE_OF_FOREIGN_LEGAL_ENTITY_ADDRESS',
}

export enum DocumentType {
  PASSPORT = 'PASSPORT',
  FOREIGN_PASSPORT = 'FOREIGN_PASSPORT',
  VISA = 'VISA',
  MIGRATION_CARD = 'MIGRATION_CARD',
  INN = 'INN',
  OGRN = 'OGRN',
  KPP = 'KPP',
} 