export enum BeneficiaryType {
  FL_RESIDENT = 'FL_RESIDENT',
  FL_NONRESIDENT = 'FL_NONRESIDENT',
  UL_RESIDENT = 'UL_RESIDENT',
  UL_NONRESIDENT = 'UL_NONRESIDENT',
  IP_RESIDENT = 'IP_RESIDENT',
  IP_NONRESIDENT = 'IP_NONRESIDENT',
  LITE_CONTACT = 'LITE_CONTACT',
}

export enum AddressType {
  REGISTRATION_ADDRESS = 'REGISTRATION_ADDRESS',
  RESIDENCE_ADDRESS = 'RESIDENCE_ADDRESS',
  LEGAL_ENTITY_ADDRESS = 'LEGAL_ENTITY_ADDRESS',
  POSTAL_ADDRESS = 'POSTAL_ADDRESS',
  OFFICE_OF_FOREIGN_LEGAL_ENTITY_ADDRESS = 'OFFICE_OF_FOREIGN_LEGAL_ENTITY_ADDRESS',
}

export enum DocumentType {
  PASSPORT = 'PASSPORT',
  FOREIGN_PASSPORT = 'FOREIGN_PASSPORT',
  VISA = 'VISA',
  MIGRATION_CARD = 'MIGRATION_CARD',
  INN = 'INN',
  OGRN = 'OGRN',
  KPP = 'KPP',
} 