export enum PaymentType {
  REGULAR = 'REGULAR',
  DEAL = 'DEAL',
  BENEFICIARY_PAYMENT = 'BENEFICIARY_PAYMENT',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
} 